### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [extenda/actions#347]
It has been noticed that while using ./iam-test-token your user-password iam-test-token-acceptance-password is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by sasjo** [comment]
This should only happen if you pass non-secret values as input variables. Is this the case here or have you managed to see a secret resolved from GCP secret manager? The primary use-case for this function is to give it secret names that are resolved using the GCP service account.

**Comment by raima-zachariah** [comment]
Thank you for the response. I was analysing a vulnerability and i was under the impression that "iam-test-token-acceptance-password" is a password you were using. Please ignore the issue and feel free to close it if that is not the case
